version: '3.7'

services:
  web:
    build: .
    command: uvicorn money_movement.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/src

  worker:
    build: .
    command: celery -A money_movement.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src